modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/mickelus/tetra/issues/new"
license="MIT"

[[mods]]
modId="tetra"
version="${file.jarVersion}"
displayName="Tetra"
authors="Mickelus"
description="Tetra revolves around modular items and attempts to blend it together with other concepts such as adventure and technology."

[[dependencies.tetra]] #optional
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra]]
    modId="mgui"
    mandatory=true
    versionRange="[3.1.2,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra]]
    modId="curios"
    mandatory=false
    versionRange="[4,)"
    ordering="AFTER"
    side="BOTH"
