modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/mickelus/tetra/issues/new"

[[mods]]
modId="tetra"
version="${file.jarVersion}"
displayName="Tetra"
authors="Mickelus"
description="Tetra revolves around modular items and attempts to blend it together with other concepts such as adventure and technology."

[[dependencies.tetra]] #optional
    modId="forge"
    mandatory=true
    versionRange="[32.0.98,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra]]
    modId="mgui"
    mandatory=true
    versionRange="[3.0.0,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra]]
    modId="curios"
    mandatory=false
    versionRange="[3.0.0.1,)"
    ordering="AFTER"
    side="BOTH"
